name: Metrics
on:
  # Met à jour les stats tous les jours à minuit
  schedule: [{cron: "0 0 * * *"}]
  # Met à jour aussi quand tu push sur la branche main/master
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Ta clé secrète
          token: ${{ secrets.METRICS_TOKEN }}

          # Options de base
          user: sharllesse  # <--- REMPLACE CECI PAR TON PSEUDO
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris
          
          # Plugin : Langages (Pour montrer C++ et C#)
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, gnuplot
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: "github"
          plugin_languages_details: bytes-size, percentage

          # Plugin : Calendrier isométrique (Ça fait très "Matrix/Pro")
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Plugin : Lignes de code (Montre que tu bosses dur)
          plugin_lines: yes
